# Generated by Django 2.2.4 on 2019-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.IntegerField(primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=100)),
                ('custage', models.IntegerField()),
                ('shopping', models.IntegerField()),
            ],
        ),
    ]
